apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-java
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-java
  template:
    metadata:
      labels:
        app: demo-java
    spec:
      containers:
        - name: demo-java
          image: marellasunil/demo-java:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: demo-java
  namespace: demo
spec:
  selector:
    app: demo-java
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
